export { default as Home } from "./home";
export { default as Vitrin } from "./vitrin/index.jsx";
export { default as Splash } from "./splash";
export { default as About } from "./about";
export { default as NotFound } from "./404";
export { default as DimentionGuide } from "./dimentionGuide";
export { default as ProductInfo } from "./productInfo/index.jsx";
export { default as Templates } from "./templates/index.jsx";
export { default as Images } from "./images";